version: '3.8'
services:
  db:
    image: postgres:15.4-alpine
    ports: 
      - 5432:5432
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - psqlvolume:/var/lib/postgresql/data
  app:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    build:
      context:
        ./
    image: app:1.0
    ports: 
      - 8080:8080
    container_name: app
    depends_on:
      db:
        condition: service_healthy
volumes:
  psqlvolume:
      